import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./components/cart/CartProvider";
import { Work_Sans, Source_Serif_4, VT323 } from "next/font/google";
import GoogleAnalytics from "./components/GoogleAnalytics";
import { GA_MEASUREMENT_ID } from "./lib/analytics";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-serif",
});

const vt323 = VT323({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${sourceSerif.variable} ${vt323.variable}`}>
        {/* Google Analytics - only loads if GA_MEASUREMENT_ID is set */}
        {GA_MEASUREMENT_ID && <GoogleAnalytics GA_MEASUREMENT_ID={GA_MEASUREMENT_ID} />}

        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}